### ISSUE TITLE
Explore boolean mental model

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#106]
E.g. make `!` equivalent to `!`: I suspect people try it and get confused by the error message. It leads to a slightly misleading mental model of how tidyselect works under the hood, but I think the fact that `-"x"` already works means that we don't need to worry too much.

And make `&` and `|` work. We also need to figure out whether to the vectorised or short-circuiting operators are the most intuitive to most people.

**Comment by hadley** [comment]
Worry: it's easy to say "I want columns `x` and `y`", but that's actually `select(df, x | y)`

**Comment by lionel-** [comment]
Maybe these operators shouldn't work with bare symbols?

Other cases should be fine, e.g. `is.numeric | is.factor`, or `starts_with("foo") & ends_with("bar")`.

**Comment by hadley** [comment]
Yeah, that makes sense - all of the other options are more obviously predicate functions.
