### ISSUE TITLE
Selecting -NULL

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#110]
https://stackoverflow.com/questions/57590111/tidy-evaluation-adding-an-argument-to-a-function-that-prevents-gathering

**Comment by moodymudskipper** [comment]
Maybe also `-rlang::missing_arg()` ?

**Comment by hadley** [comment]
I'm not sure this is needed given that you can use `integer()`:

``` r
tidyselect::vars_select(names(mtcars), integer())
#> named character(0)
tidyselect::vars_select(names(mtcars), -integer())
#>    mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear 
#>  "mpg"  "cyl" "disp"   "hp" "drat"   "wt" "qsec"   "vs"   "am" "gear" 
#>   carb 
#> "carb"
```

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This would be nice for `NULL` defaults in function arguments. We have done similar changes elsewhere to make it easier to interface with `NULL` defaults (facets in ggplot IIRC).

**Comment by hadley** [comment]
I think making `-NULL` work is that way would be in conflict with https://github.com/tidyverse/principles/issues/24, and I don't think this case is compelling enough to violate the principle (given that there are two existing work arounds).

If we just want to solve the default value problem, I'd be in favour of:

```R
nothing <- function() integer()
```

And adding a couple of tests to ensure that this behaviour is locked in.

**Comment by lionel-** [comment]
I was thinking about the principle of treating `NULL` as an absent input.

Though I guess this principle would favour making this work actually:

```
vars_select(letters, -one_of(NULL))
```

**Comment by lionel-** [comment]
I like `nothing()` but is it worth it to use up this symbol for such a corner case? Maybe it could also be used for teaching about vectors in R, e.g. `letters[nothing()]` creates a prototype.

Let's keep thinking about this, in the meantime I will recommend your solution of using `integer()` for default arguments. I'll also make `one_of(NULL)` be equivalent to `one_of()`.
