### ISSUE TITLE
`vars_select()` performance with many names

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tidyselect#111]
Note that this directly affects the performance of `dplyr::select()`

`vars_select()` is rather slow with many column names:

```r
library(tidyselect)
cnames <- paste0("c", 1:100000)

t1 <- proc.time()
x <- vars_select(cnames, "c1")
proc.time() - t1
#>    user  system elapsed 
#>  42.986   0.093  43.135
```

The main slowdown currently is a call to `child_env()` in `vars_select_eval()`:
https://github.com/r-lib/tidyselect/blob/4de95ee641b68f7ab098816d01e02737afa2410c/R/vars-select.R#L234

Replacing that line with the following is a _potential_ solution:

```r
  #data_env <- child_env(data_helpers_env, !!!data)
  data_env <- new_environment(parent = data_helpers_env)
  env_bind_lazy(data_env, !!!data)
```

After:

``` r
library(tidyselect)
cnames <- paste0("c", 1:100000)

t1 <- proc.time()
x <- vars_select(cnames, "c1")
proc.time() - t1
#>    user  system elapsed 
#>   1.048   0.015   1.064
```

**Comment by DavisVaughan** [comment]
This particular slow down was completely solved by https://github.com/r-lib/rlang/issues/827

**Comment by hadley** [comment]
It's probably worth bumping the required version of rlang here

**Comment by lionel-** [comment]
Is it worth making dev tidyselect depend on dev rlang just for a performance resolution? I would have thought not.

**Comment by hadley** [comment]
For a performance resolution of this magnitude? I'd consider it

**Comment by hadley** [comment]
BTW a bit of profiling suggests that you can ~double the speed again by eliminating the use of `::` in the default `binder`

**Comment by lionel-** [comment]
oh the requirement is for users, not developers, got it.

> BTW a bit of profiling suggests that you can ~double the speed again by eliminating the use of :: in the default binder

Also I think `env_bind()` should be rewritten in C given its primitive nature.

**Comment by hadley** [comment]
Actually just doing:

```R
    binder <- function(env, nm, value) {
      env$nm <- value
    }
```

Makes it even faster - from 1.2s to 0.18s for @DavisVaughan's example:

```R
library(tidyselect)
cnames <- paste0("c", 1:100000)
bench::system_time(vars_select(cnames, "c1"))
```

**Comment by lionel-** [comment]
We might not want to dispatch to `[[<-` though. Going through `Rf_defineVar()` seems preferable.

**Comment by hadley** [comment]
I don't think `[[` will dispatch when called on an environment? I suspect `Rf_defineVar()` won't be much faster; and `[[` gives a decent performance boost for very little effort.

**Comment by DavisVaughan** [comment]
The `[[<-` environment case is in the default fallthrough, and is even special cased as the first case that get's run https://github.com/wch/r-source/blob/cda88629f79855407de4471e57edf0564fba87d4/src/main/subassign.c#L1784

**Comment by lionel-** [comment]
`[[<-` does dispatch on environments.

**Comment by lionel-** [comment]
We now depend on dev rlang.
