### ISSUE TITLE
Support for packed tibbles

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#112]
Unclear how it should work.

Should we search for terms across all nested tibbles? Seems to work best with prototype interface, so we can return the selected names with structure.

How do we pull variables out of their nested tibbles? Maybe:

```r
data %>% select(foo, nested$var)
```

We'd need to figure out auto-naming so that `nested$var` is named as `var`.

**Comment by jcheng5** [comment]
@rich-iannone and I are thinking about how to make use of packed tibbles from the gt package.

gt uses tidyselect to make formatting directives apply to specific columns (e.g. fmt_number below):

```r
library(gt)
library(dplyr)

mtcars %>%
  select(cyl, hp) %>%
  gt() %>%
  fmt_number(columns = vars(hp), decimals = 0)
```

Now with packed tibbles:

```r
mtcars %>%
  select(cyl, hp, mpg) %>%
  group_by(cyl) %>%
  summarise(
    across(where(is.numeric), ~tibble(median = median(.), min = min(.), max = max(.)))
  ) %>%
  gt() %>%
  fmt_numeric(columns = ???)
```

This isn't the end of the world for gt, we can just ask people to `tidyr::unpack()` before calling gt, but I thought before we gave up we'd at least ask if there was some direction you were thinking of going before you closed this issue.

**Comment by lionel-** [comment]
This would probably require a new operator because the return type would be different (list [of lists] of positions). You would like to get the positions of all matching columns in all df-cols right?

```
df <- tibble(x = tibble(x = "foo", y = "bar"), w = "baz", y = "quux")
eval_select_deep(quote(y), df)
#> $x
#> $x$y
#> [1] 2
#> 
#> $y
#> [1] 3
```

With the renaming syntax, only the inner locations would be renamed.

**Comment by hadley** [comment]
We're currently not planning to add support for packed tibbles to tidyselect because user uptake has been pretty low, and we're generally moving away from them again. We still believe they're a nice data structure, but not something we'd generally want to expose to users, and hence we don't feel compelled to support them in our user facing infrastructure.
