### ISSUE TITLE
- inconsistency 

### ISSUE THREAD

**Issue by jeffreypullin** [r-lib/tidyselect#132]
Hi Lionel, 

Firstly, thanks for all your work on tidyselect!

I recently observed the following behaviour which I found quite odd:

``` r
library(tidyselect)

vars_select(names(iris), ends_with("Length"), -Sepal.Length)
#>   Petal.Length 
#> "Petal.Length"
vars_select(names(iris), -Sepal.Length, ends_with("Length"))
#>    Sepal.Width   Petal.Length    Petal.Width        Species 
#>  "Sepal.Width" "Petal.Length"  "Petal.Width"      "Species"
```

<sup>Created on 2019-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You also get the same behaviour if you replace the comma with the new `|` operator. I would expect that (to put if formally) the comma is a commutative operator. 

This is with the current `tidyselect` master from github.

**Comment by lionel-** [comment]
`foo, -bar` is syntax for `setdiff(foo, bar)`, so it's not commutative.

I think we'll introduce binary `-`, the semantics should be clearer.

**Comment by lionel-** [comment]
Also if there is no LHS, i.e. if the first input is a `-` input, there is an implicit `everything()`. So `select(-foo, bar)` is syntax for `select(union(setdiff(everything(), foo), bar))`.

**Comment by lionel-** [comment]
(Don't experiment too much with this on current master, I borked the semantics while switching from C++ to R. I only recently understood what `,` and `-` are really syntax for...)
