### ISSUE TITLE
User-friendly description of the syntax

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#141]

**Comment by JosiahParry** [comment]
One of the reasons I find the `tidyselect` helpers to be difficult to grasp is the documentation around it. The entirety of the package (at least to my knowledge) shares the same help page. I believe differentiating help pages would make the functions more easily accessible.

**Comment by JosiahParry** [comment]
🥳 🎈 🍾 
Excited! Thanks :)
