### ISSUE TITLE
porting documentation from dplyr, etc.

### ISSUE THREAD

**Issue by AHoerner** [r-lib/tidyselect#142]
Not sure if this is the same issue as lionel's #141, but it seems to me that with transfer of the select functions in dplyr and many other tidyverse packages to tidyselect, appropriate portions of the documentation should be transferred or copied as well,, especially as we now get errors identified as originating in tidyselect functions. For example, I just got an "Error: No tidyselect variables were registered" error from tidyr::pivot_longer. I know why, but identifying the right documentation was awkward.

**Comment by lionel-** [comment]
The error message no longer refers to tidyselect:

```r
dplyr::contains("foo")
#> Error: `contains()` must be used within a *selecting* function.
```
