### ISSUE TITLE
Inconsistent error for column not found when using rlang with vars_pull

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/tidyselect#154]
Found as a side-effect of an issue raised whilst building a reprex on tidyr.

We're trying to call tidyselect but specifying a column which is missing (or mis-spelt, or whatever). As a user, you want a friendly error that helps you realise the mistake you've made.

Here we first of all make the mistake using the call directly (in this case our tibble has columns a and b, but we've asked for c). The returned error makes it easy to realise the mistake.

In the second example however we've passed our incorrect column name as a parameter in a function. The end result is a less-friendly error which makes it much harder to realise what the error is.

``` r
library(tibble)
library(rlang)

df <- tibble::tibble(a = 1:2, b = 3:4)

tidyselect::vars_pull(names(df), "c")
#> Error: Strings must match column names. Unknown columns: c

missing_column_demo_fun <- function(df, col) {
  col <- ensym(col)
  tidyselect::vars_pull(names(df), !!enquo(col))
}

missing_column_demo_fun(df, "c")
#> Error in eval_tidy(enquo(var), var_env): object 'c' not found
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
We can't really throw an out-of-bounds error since the object is evaluated in the context as well, and we can't really deprecate evaluation in the environment in the same way we did for selections, because we don't have a clear alternative yet (besides unquoting). So unfortunately this won't be fixed in the short term.

**Comment by lionel-** [comment]
But we could at least remove the eval-tidy call from the error.
