### ISSUE TITLE
Regression bug: select_(-1*one_of()) now fails

### ISSUE THREAD

**Issue by daattali** [r-lib/tidyselect#159]
I know that select_ is old syntax but I looked at the changelog's breaking changes and this didn't seem to be one of the expected changes.

The following code works with the CRAN version but fails with the development version:

```
cols <- c("mpg", "cyl")
dir <- -1
dplyr::select_(mtcars, ~(dir * dplyr::one_of(cols)))
```

With the error

```
Error: Can't use arithmetic operator `*` in selection context.
```

The multiplication here is used as a way to [either select or deselect columns](https://github.com/daattali/ddpcr/blob/92bdff0080da1cc007c800b029cbdccbb8418a24/R/utils.R#L372-L385) by setting `dir` to either 1 or -1

**Comment by daattali** [comment]
So is there a way to recreate the behaviour of `dplyr::select_(mtcars, ~(dir * dplyr::one_of(cols)))` with the new tidyselect? Or is it not possible to achieve both select and deselect in one line of code?

**Comment by lionel-** [comment]
We could add support for `if()` in the interpreter. The condition would be interpreted as an env-expression and the two branches as data-expressions. Then you could do:

```r
dplyr::select(mtcars, if (sel) all_of(cols) else !any_of(cols))
```

What do you think @hadley?

**Comment by daattali** [comment]
Oof, that's a huge design decision, I'll stay out of this. I already fixed
the issue in my package and it now works with new tidyselect, so feel free
to close this issue if you don't think this should be done.

**Comment by lionel-** [comment]
It is a rather straightforward extension I think, but let's see if the need comes up again then.
