### ISSUE TITLE
Deprecate `.data` in data-expressions

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#169]
To make programming with data-masking and programming with selections completely distinct.

**Comment by lionel-** [comment]
Do we need an `all_of()` variant that expects exactly 1 variable?

**Comment by dblodgett-usgs** [comment]
Out of curiosity, was the fact that this pattern has been recommended in this vignette https://dplyr.tidyverse.org/articles/programming.html for quite some time taken into account when this change was made? It seems like it's causing a lot of people to go changing a lot of code ... is it really needed?

**Comment by hadley** [comment]
@dblodgett-usgs yes

**Comment by dblodgett-usgs** [comment]
Well ok then, thanks I guess.

**Comment by chrarnold** [comment]
I'd like to know what the best way is regarding this change when it comes to warnings during R CMD check? I recently added .data$ to eliminate the warnings during package checking, but with the newest package versions, look like I need to revert back. Couldnt find it anywhere or I oversaw? Thanks!

**Comment by hadley** [comment]
The warning message should tell you what to do:

``` r
out <- mtcars |> dplyr::select(.data$cyl)
#> Warning: Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
#> ℹ Please use `"cyl"` instead of `.data$cyl`
```

<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chrarnold** [comment]
Sorry maybe I was not clear, the warning message is absolutely clear. However, when building packages, R CMD check prints the almighty famous "no visible binding for global variable" note for each instance when not using the .data$ prefix. Before this change, I found the .data$ construct to be the best to avoid this note, I didnt like defining dozens of global variables. Is there any updated recommendation on this in light of this change?

**Comment by dblodgett-usgs** [comment]
@chrarnold -- this article was updated recently and has a pretty thorough summary of the details on this. https://dplyr.tidyverse.org/articles/programming.html#data-masking In short, use .data$foo for things that do not use tidyselect and "foo" for things that do use tidyselect. Which function is throwing the error should be a guide but for me it was basically select/rename use "foo" and filter/mutate/group_by use .data$foo. See https://github.com/DOI-USGS/nhdplusTools/issues/306 for my clean up issue on this if it helps.

**Comment by lionel-** [comment]
@chrarnold If you use `dplyr::select("cyl")` (with quotes) instead of `dplyr::select(.data$cyl)`, there will be no warnings.

**Comment by chrarnold** [comment]
Thanks @lionel- and @dblodgett-usgs , I didnt know `dplyr::select("cyl")` can be used, does this work only for newer versions of dplyr or this was already supported for older versions? For the package, I have to find an implementation that is as generically working as possible without having to require particular package versions etc if possible.

@dblodgett-usgs In a tidyselect context, wouldnt the R CMD check notes still be there then? I really want to get rid of these notes, having hundreds of them bloats up the output so much

**Comment by lionel-** [comment]
This was also supported in old versions of dplyr.

> @dblodgett-usgs In a tidyselect context, wouldnt the R CMD check notes still be there then?

No because in tidyselect contexts you now use quoted names like `"foo"` as @dblodgett-usgs mentioned.

**Comment by chrarnold** [comment]
Thanks, I have not read the "new" quoted recommendation anywhere else to be honest, also not in the quoted (and updated) https://dplyr.tidyverse.org/articles/programming.html#data-masking article. I'll update my code correspondingly!

**Comment by lionel-** [comment]
@chrarnold To be clear, in data-masking (as in the link you just shared), a string represents a string, not a column. So you can't do things like `1 + "cyl"` because you'd be adding a number to a string.

It's only for column selection that you can refer to a column with a string.

**Comment by shahronak47** [comment]
@lionel- Then what is the recommended way to replace `.data` in `mutate` ? Since `.data` is deprecated we can't use `mtcars %>% mutate(new = 1 + .data$cyl)` or `mtcars %>% mutate(new = 1 + .data[["cyl"]])`

**Comment by lionel-** [comment]
`.data` is __not__ deprecated in `mutate()`.

It's only been deprecated in tidy selections, e.g. in contexts like `select(...)` or `pivot_longer(cols = )`.
