### ISSUE TITLE
problem with glue

### ISSUE THREAD

**Issue by sylvaine31** [r-lib/tidyselect#170]
Hi, 
I updated this morning `rlang`package version 0.4.3. I have now problems with my old scripts using `glue::glue` with the folowing message: 

> Erreur : Must extract column with a single subscript.
> x The subscript `var` has the wrong type `glue`.
> i It must be numeric or character.
> Run `rlang::last_error()` to see where the error occurred.
> Called from: rlang:::signal_abort(x)

I have now to add a `as.character()` to all results from `glue::glue`. Is that an expected behaviour?

**Comment by lionel-** [comment]
Reprex:

```r
select(iris, glue::glue("Species"))
#> Error: Must subset columns with a valid subscript vector.
#> ✖ The subscript has the wrong type `glue`.
#> ℹ It must be numeric or character.
```

@sylvaine31 Until we resolve this you can add the following set of methods in the global environment as a workaround, this should allow glue vectors to be treated as character vectors:

```r
vec_ptype2.glue <- function(x, y, ...) UseMethod("vec_ptype2.glue", y)
vec_ptype2.glue.character <- function(x, y, ...) x
vec_ptype2.glue.default <- function(x, y, ...) vctrs::vec_default_ptype2(x, y)
vec_ptype2.character.glue <- function(x, y, ...) y
vec_cast.character.glue <- function(x, to, ...) unclass(x)
```

**Comment by lionel-** [comment]
Add an emoji to this post if you're having the same issue.

**Comment by sylvaine31** [comment]
Hi Victor, 
Without the set of methods, I have still the same error message than your reprex, but with the set of methods, everything is OK. 
Thanks.
