### ISSUE TITLE
tidyselect v1.0.0 CRAN Windows binary not available

### ISSUE THREAD

**Issue by ddsjoberg** [r-lib/tidyselect#171]
Hello! tidyselect is awesome!

My co-authors and I are releasing a updated version of our package next week.  We currently re-export the tidyselect helpers, and were planning on including the new helpers, `all_of()` and `any_of()`, in the next release.

Since the release of tidyselect v1.0.0 I see CRAN hasn't updated the Windows binaries for R 3.6, and the CRAN checks failed for a Windows build.  I am hesitant to release an updated version that requires a tidyselect install from source for Windows users when there may be an issue installing on Windows.  

Can I ask your advice, please?  Should I release our package now with a tidyselect 1.0.0 dependency, or wait until the Windows builds are ready to go? There is a good chance I am misreading the CRAN results, and this is nothing to be concerned about.  

Thank you so much for your input!

**Comment by lionel-** [comment]
This is only a problem on the CRAN machine, we have to wait until the machine makes another attempt. It might be annoying for your users to have to install tidyselect from source. On the upside, building tidyselect doesn't require Rtools because it's an R-only package.

**Comment by ddsjoberg** [comment]
Thank you kindly for the reply!  I'll include the updated version of tidyselect in our package.
