### ISSUE TITLE
inconsistent error message for non-existant columns depending on tidyselect syntax

### ISSUE THREAD

**Issue by zkamvar** [r-lib/tidyselect#172]
Similar to #154, but a bit different in that the error message is ultimately the same, but if the user supplies several incorrect column names as barewords (not sure how to refer to these), they are only informed about the first one as opposed if they use a character vector and `all_of()`, where they are presented with all of the incorrect names,

Here's a modified example from the [get started vignette](https://tidyselect.r-lib.org/articles/tidyselect.html) (note that the same result is found with `dplyr::select()`):

``` r
wrapper <- function(data, ...) {
  tidyselect::eval_rename(rlang::expr(c(...)), data)
}
```

User supplies barewords, only the first incorrect one is reported

```r
wrapper(mtcars, mpg, cyl, horses, back)
#> Error: Can't rename columns that don't exist.
#> ✖ The column `horses` doesn't exist.
```

User supplies character vector, all incorrect are reported
```r
SEL <- c("mpg", "cyl", "horses", "back")
wrapper(mtcars, tidyselect::all_of(SEL))
#> Error: Can't rename columns that don't exist.
#> ✖ The columns `horses` and `back` don't exist.
```

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Apologies in advance if this is too edge-case.

**Comment by lionel-** [comment]
I think it would be hard to solve this, so unfortunately we have to accept this inconsistency as part of the design.
