### ISSUE TITLE
eval_select: names() vs colnames()

### ISSUE THREAD

**Issue by karldw** [r-lib/tidyselect#177]
Seeing that `vars_select` is on a path to deprecation, I started to transition to `eval_select`, but I've run into an issue with remote tables, where `names()` and `colnames()` differ. Here's an example:

``` r

fn_eval_select <- function(.x, ...) {
  pos <- tidyselect::eval_select(rlang::expr(c(...)), .x)
  colnames(.x)[pos]
}

fn_vars_select <- function(.x, ...) {
   unname(tidyselect::vars_select(colnames(.x), ...))
}

Loblolly_mem <- dbplyr::tbl_memdb(Loblolly)

# Same for local data:
fn_eval_select(Loblolly, dplyr::starts_with("S"))
#> [1] "Seed"
fn_vars_select(Loblolly, dplyr::starts_with("S"))
#> [1] "Seed"

# Issues for remote data because eval_select calls names()
fn_vars_select(Loblolly_mem, dplyr::starts_with("S"))
#> [1] "Seed"
fn_eval_select(Loblolly_mem, dplyr::starts_with("S"))
#> Error: `x` must be a vector, not a `tbl_SQLiteConnection/tbl_dbi/tbl_sql/tbl_lazy/tbl` object
```

One way to avoid these issues would be to use `colnames()` instead of `names()` [here](https://github.com/r-lib/tidyselect/blob/76099387fc7db717cb3a66316f31964dd22f3e25/R/eval-select.R#L101). What do you think?

**Comment by hadley** [comment]
In general, I don't think you should expect `names()` and `colnames()` to return different things. Instead you should create a small data frame (e.g. with `collect(x, 0)`) and pass that to `eval_select()`.
