### ISSUE TITLE
Support multiple conditions for select helpers (e.g. `starts_with("a", "b")`

### ISSUE THREAD

**Issue by jlegewie** [r-lib/tidyselect#179]
Hi,

it would be great if all the select helpers support multiple conditions. Here is an example:

```
d <- tibble(a_1 = 1:10, a_2 = 1:10, b_1 = 1:10, b_2 = 1:10)
# This works
d %>% select(starts_with("a"), starts_with("a"))
# It would be great if this works as well
d %>% dplyr::select(starts_with("a", "b"))
```

I know that there are easy solutions to this with multiple `starts_with` or `matches` etc. But the select helpers are all about making it easier to select columns and I think this would be a really nice improvement.

Thanks for considering!

**Comment by hadley** [comment]
Did you try this? 😉

**Comment by jlegewie** [comment]
Yes, I get this error `Error: argument is not interpretable as logical` on `tidyselect` 1.0.0.9000 and `dplyr` 0.8.99.9002

```
rlang::last_error()
<error/rlang_error>
argument is not interpretable as logical
Backtrace:
  9. dplyr::select(., starts_with("a", "b"))
 11. tidyselect::eval_select(expr(c(...)), .data)
 12. tidyselect:::eval_select_impl(...)
 13. tidyselect:::with_subscript_errors(...)
Run `rlang::last_trace()` to see the full context.
```

**Comment by hadley** [comment]
WFM:

``` r
packageVersion("dplyr")
#> [1] '0.8.99.9002'
packageVersion("tidyselect")
#> [1] '1.0.0'
dplyr::select(head(mtcars), starts_with(c("v", "m")))
#>                   vs  mpg
#> Mazda RX4          0 21.0
#> Mazda RX4 Wag      0 21.0
#> Datsun 710         1 22.8
#> Hornet 4 Drive     1 21.4
#> Hornet Sportabout  0 18.7
#> Valiant            1 18.1
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Oh, you need to provide a vector; not supply different arguments.
