### ISSUE TITLE
Add example combining named and dots inputs

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/tidyselect#182]
Hi dev team,

I noticed a strange side effect when using `eval_select`: the result is attributed in the variable called as `expr`.

I need to concatenate my first argument with the ellipsis for some ugly design that I don't know how to do any other way yet.

```
foo = function(x, ...){
    # print(x) #throws an error as "everything()" is not printable
    y = eval_select(expr(c(x, ...)), data = iris)
    print(x)
    return(y)
}
foo(everything())
# [1] 1 2 3 4 5
# Sepal.Length  Sepal.Width Petal.Length  Petal.Width      Species 
# 1            2            3            4            5 
```

As you can see, after the `eval_select` call, `x`'s value has changed to `unname(y)`, while there was no attribution anywhere.

Is this normal behavior?

ADVERTISEMENT: any help on that would be most welcome `-->` [StackOverflow question](https://stackoverflow.com/questions/60804580/how-to-initialize-a-variable-with-a-tidyselect-helper)

**Comment by lionel-** [comment]
That's complicated. Selection helpers like `everything()` or `starts_with()` don't need to be tunnelled with `{{` because of the way they are implemented. Other tidyselect features do need tunnelling.

If you don't tunnel, the `x` promise is assigned the result of the argument evaluation. `everything()` returns the location vector, which is what you see.

**Comment by DanChaltiel** [comment]
I based my code on the `eval_select` help example. This works with and without curly-curly the exact same, why is it important to use it?

**Comment by lionel-** [comment]
* Passing a variable without going through `all_of()` is deprecated, you should be seeing warnings.

* Only selection helpers that inspect the _dynamic_ context will work. But that's purely an implementation detail.

* Other features like `&` and `-` won't work.

**Comment by lionel-** [comment]
Reopening to remember to add an example combining named and `...` inputs.
