### ISSUE TITLE
Add an option to display warnings more than once per session 

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/tidyselect#184]
Would it be possible to add a global option to force `tidyselect` to show the following warning every time it is needed and not once per session?

> ```
> Note: Using an external vector in selections is ambiguous.
> i Use `all_of(my_var)` instead of `my_var` to silence this message.
> i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
> ```

I want to do things right and add this `all_of(my_var)` but I don't know which part of my code threw it and I used this variable name in many different places so I cannot see where it is missing.

Reading [this tibble issue](https://github.com/tidyverse/tibble/issues/620), I tried the following lines out of luck but they didn't work.

> ```
> options(tidyselect_warnings_as_errors = TRUE)
> options(tidyselect_repeat_warnings = TRUE)
> ```

Thanks
Dan

**Comment by lionel-** [comment]
`options(tidyselect_verbosity = "verbose")` should do it.

**Comment by DanChaltiel** [comment]
Sorry but it did not.

Here is an MRE:

```r
options(tidyselect_verbosity = "verbose")
XX=c("Sepal.Length", "Sepal.Width")
tidyselect::vars_select(names(iris), XX)
```
This produces a warning only once per session.

**Comment by hadley** [comment]
The problem is that `eval_sym()` calls `inform_once()` regardless of the status.

@DanChaltiel you'd be well served by learning how to make reprexes. Here's a reprex that actually illustrates the problem:

``` r
library(tidyselect)
options(tidyselect_verbosity = "verbose")

vars <- "a"
vars_select(letters, vars)
#> Note: Using an external vector in selections is ambiguous.
#> ℹ Use `all_of(vars)` instead of `vars` to silence this message.
#> ℹ See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
#> This message is displayed once per session.
#>   a 
#> "a"
vars_select(letters, vars)
#>   a 
#> "a"
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
