### ISSUE TITLE
Add role concept similar to recipes package

### ISSUE THREAD

**Issue by jfsalzmann** [r-lib/tidyselect#185]
Suggestion:

Add a role concept to tidyselect so that in the tidyverse one can select columns/variables not only based on column types or column names, but also specify roles (e.g. "predictor", "response") as well as use this in conjunction with names & types.

Aim: make selections like the following possible:

- select all predictors
- select all numeric predictors starting with "x_"

https://www.rdocumentation.org/packages/recipes/versions/0.1.9/topics/has_role

(Disclaimer: Neither do I have the skills to contribute to tidyselect development myself, nor am I sure if in the tidyverse architecture tidyselect would be the right package to add such a feature - pls advice me where to suggest this concept otherwise)

**Comment by hadley** [comment]
This is out of scope for tidyselect, sorry.

**Comment by jfsalzmann** [comment]
@hadley Thank you for letting me know. Would you be able to give me a hint where in the tidyverse architecture this kind of a concept could be suggested instead? Tibble?

Or do I miss an existing, similar concept that would enable me to store column meta data other than using column name prefixes?

Thanks!

**Comment by lionel-** [comment]
The right place for adding roles is in the package that would define the roles. This doesn't fit in the tidyverse.

But instead of relying on externally defined roles, I would try to rely on internally defined types and attributes. You can now use predicate functions to select columns: `iris %>% select(where(is.factor))`.

**Comment by jfsalzmann** [comment]
Thanks @lionel- ! 

Given that types would not help, how would I use attributes as you mentioned?

Lets say I have `frequency` and `size_1`, `size_2` ..., `size_20`, all of them being numeric, so type-based selection would not work. But I need to be able to distinguish between `frequency` and the others as `frequency` would be a weighting variable, all size variables would be predictors. (Simple example, but the case could also be much more complex with larger numbers of roles and variables belonging to them).

In case I would not want to rely on the column names to discriminate, and types were the same. How could I then make use of attributes within the tidyverse logic? I have never seen how to define/retrieve them or use it as filter.

Even if someone would want to implement a package for that, I don't see how storage of such metadata would work within tidyverse / tibbles.

I could not find this `where()` function in the docs, I would be very thankful if you sent me a link.
Thx!

**Comment by lionel-** [comment]
Regarding `where()`, see https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-select-rename-relocate/ and https://tidyselect.r-lib.org/reference/where.html

At a high level I think there are three ways to go about it:

- Record the attributes in a special data structure (maybe a data frame, maybe something else like a recipe) and then provide selection helpers to query these attributes. I think this is tricky and probably best avoided.

- Record the attributes in the vector types. vctrs would help with this, but documentation is still lacking.

- Encode the attributes in the names and use name-based selection.

I recommend the third option. Sorry I can't help more.
