### ISSUE TITLE
Export `where()`

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/tidyselect#201]
I was trying to reexport `where()` for my package that uses tidyselect, but the function isn't currently exported in v1.1.0.

``` r
library(tidyselect)

tidyselect::where
#> Error: 'where' is not an exported object from 'namespace:tidyselect'
```

**Comment by lionel-** [comment]
This is on purpose, for now.

**Comment by markfairbanks** [comment]
Ah gotcha. Is there a reason for this?

I currently have functions that have defaults like `cols = c(where(is.character))` that throw warnings using `devtools::check()`. Using the bare form `cols = c(is.character)` is also flagged due to the warnings `tidyselect` generates.

**Comment by lionel-** [comment]
Just hesitance regarding using up a good function name. I think we'll end up exporting it anyway, since it'd probably be confusing to have different functionality for the same symbol. R CMD check note is a good point (altough easy to work around).

**Comment by emeyers** [comment]
> Just hesitance regarding using up a good function name. I think we'll end up exporting it anyway, since it'd probably be confusing to have different functionality for the same symbol. R CMD check note is a good point (altough easy to work around).

Sorry, this might be a naive question because I'm new to creating packages, but I was wondering what is the recommended work around for dealing with this R CMD check note?

**Comment by CorradoLanera** [comment]
`devtools::check()` signals both usages:

E.g., assume it is used inside a `dplyr::select()` call as:
- `tidyselect::where(<something>)`: NOTE: Missing or unexported object: ‘tidyselect::where’
- `where(<something>)`: NOTE: no visible global function definition for ‘where’

How should we use `{dplyr}` & co. into a package using `where` and passing the checks? Should we Import `{tidyselect}`, or not?

**Comment by lionel-** [comment]
`utils::globalVariables("where")` for now.

**Comment by williamlief** [comment]
I just ran into the same issue with re-exporting `tidyselect::where` in my package. It would be nice if a note could be added to the documentation for `where` about this issue (my apologies if such a note does exist in the documentation and I just did not see it).

**Comment by lhmet** [comment]
I managed to make it work by doing:

1. Ensuring that the tidyselect dependency has been added to DESCRIPTION: `usethis :: use_package (" tidyselect ")`

2. Calling it using `tidyselect::vars_select_helpers$where` or Importing it using
# '@importFrom tidyselect vars_select_helpers

**Comment by lionel-** [comment]
@lhmet I would really recommend this instead:

```r
utils::globalVariables("where")
```

`globalVariables()` is often the right and correct answer to static analysis problems with NSE functions.

**Comment by sclewis23** [comment]
Any idea when you will export where?

**Comment by lionel-** [comment]
Probably in the next version, but that's not high priority because the workaround is easy and non-invasive.

**Comment by NateNohling** [comment]
Writing my first package and still struggling with where() even after reading this thread. 

I added this line into the function to define where, and then later call where(!is.list) in the function and it passes the CMD check fine.
`where <- utils::globalVariables("where")`

But when I run the package, I get an error.

> Error in registerNames(names, package, ".__global__", add) : 
  The namespace for package "functions" is locked; no changes in the global variables list may be made. 

Any ideas or updates on when we can just put tidyselect::where() into packages?

**Comment by lionel-** [comment]
Hello. You shouldn't assign `where`. Change this:

```r
 where <- utils::globalVariables("where")
```

Into:

```r
utils::globalVariables("where")
```

I don't know why you're getting this error message though. Where did you put the `globalVariables()` call? And what do you mean by "run the package"?

**Comment by petrbouchal** [comment]
@NateNohling @lionel- I ran into the same error because I put `utils::globalVariables("where")` inside a function definition - it needs to go outside. Apparently this is mentioned somewhere in the help page but I also had a hard time finding out where to put the call. See https://stackoverflow.com/questions/40251801/how-to-use-utilsglobalvariables.

**Comment by NateNohling** [comment]
@petrbouchal Ah...got it! That fixed it! Thanks

**Comment by evanmascitti** [comment]
How does one actually _call_  this function inside a package once it is OK'd with `utils::globalVariables()`  ? If using no accessor, I receive the message "can't find function `where()`. If I use `:::` I still get a note from R CMD CHECK saying the `:::` operator is frowned upon.

**Comment by lionel-** [comment]
`where()` is not meant to be evaluated by the R interpreter, only by the tidyselect interpreter. Selections are a DSL on top of R. (Unlike data-masking which is pure R)

**Comment by dkgaraujo** [comment]
Just coming here to add to the call for exporting `where` 😀.

**Comment by ramiromagno** [comment]
Idem.

**Comment by peterjuv** [comment]
Idem :)

**Comment by SimonDedman** [comment]
So per @petrbouchal 's link: add
`#' @import utils`
to the function param block, and
`utils::globalVariables("where")`
within the function script

idem / +1 / samesies for exporting please. Cheers!

**Comment by jjesusfilho** [comment]
> It is likely that `where()` will be superseded in favour of anonymous functions, see #248.

I haven't been able to replace `where()` with an anonymous function in this case:

```
df <- df |> 
  dplyr::select(!where(~all(is.na(.x))))

```

**Comment by paladinic** [comment]
would discard() work?
[example found here](https://www.codingprof.com/3-easy-ways-to-remove-empty-columns-in-r/)
