### ISSUE TITLE
Can `where(predicate_a | predicate_b)` be supported?

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/tidyselect#202]
When boolean operators were introduced, they made sense as tidyselect supports the bare functions so we could write:

``` r
select(is.factor | is.numeric)
```

but, now we have to write:

``` r
select(where(is.factor) | where(is.numeric))
```

Looking at https://github.com/r-lib/tidyselect/issues/106#issuecomment-521521523, `|` and `&` were intended to work only with functions (though now it works just as same as `c()`). So, I feel it's natural that we can use `|` to combine functions directly, though I'm not sure if this change is worth implementing, considering the complexity.

**Comment by yutannihilation** [comment]
Negation inside `where()` might be also worth considering.

e.g.

``` r
select(where(!is.factor))
```

instead of

``` r
select(!where(is.factor))
```

**Comment by lionel-** [comment]
Yes we have plans to make it work without `where()` at least in `across()`, and have considered inside boolean operators as well. For the latter it's not clear whether it's worth it, the risk is that it might not be obvious for users when to use `where()`.

**Comment by yutannihilation** [comment]
Thanks. If you are redesigning the interface, I'll just wait for the conclusion. Should I close this issue?

**Comment by lionel-** [comment]
We can leave it open thanks!

**Comment by markfairbanks** [comment]
> Yes we have plans to make it work without where() at least in across()

If this feature is added to `across()` (but not other functions) will there be something like an added arg to `eval_select()` so package developers can use it as well? Something similar to `allow_rename`, but to safely do predicate selection?

**Comment by MyKo101** [comment]
Not sure how useful this would be if you are redesigning the interface anyway, but I think the syntax here is clear, and so if you are planning on keeping `where()` in some places, they might be useable:
```
where_all <- function(...){
  .fns <- lapply(list(...),rlang::as_function)
  call_fns <- function(f,...) f(...)
  function(...) Reduce(`&`,lapply(.fns,call_fns,...))
}

where_any <- function(...){
  .fns <- lapply(list(...),rlang::as_function)
  call_fns <- function(f,...) f(...)
  function(...) Reduce(`|`,lapply(.fns,call_fns,...))
}

where_not <- function(fn){
  predicate <- rlang::as_function(fn)
  function(...) !(predicate(...))
}
```
They'd obviously need a check in there to make sure the output is boolean and they might need some sort of optimisation. But, they're also nesatble. Examples:

```
condition_1 <- function(x) 1 %in% x
condition_2 <- function(x) 2 %in% x
condition_3 <- function(x) 3 %in% x

df <- tibble(
  x_ttt = c(1,2,3),
  x_ttf = c(1,2,4), 
  x_tft = c(1,3,4),
  x_tff = c(1,4,5),
  x_ftt = c(2,3,4),
  x_ftf = c(2,4,5), 
  x_fft = c(3,4,5),
  x_fff = c(4,5,6)
)

# 1 & 2
df %>%
  summarise(across(where_all(condition_1,condition_2),sum))

# 1 | 2
df %>%
  summarise(across(where_any(condition_1,condition_2),sum))

# !1
df %>%
  summarise(across(where_not(condition_1),sum))

# 1 & 2 & !3
df %>%
  summarise(across(where_all(condition_1,condition_2,
                             where_not(condition_3)),sum))

# 1 & (2 | 3)
df %>%
  summarise(across(where_all(condition_1,
                             where_any(condition_2,condition_3)),sum))
```

**Comment by lionel-** [comment]
@MyKo101 Another option we've considered is to export `or()` and `and()` predicate constructors from purrr for these cases.

**Comment by MyKo101** [comment]
Have these constructors been implemented yet? Can't see them in the `{purrr}` github. Closest I could find was `every()` and `some()`, but I don't think they work as I think this Issue wants. I thought they applied the same predicate to multiple elements in a list (or columns in a data.frame), whereas here we'd need to apply multiple predicates to the same element.

**Comment by lionel-** [comment]
They don't exist in purrr yet.

**Comment by lionel-** [comment]
I think we'll first assess how anonymous functions are solving that need (#248).

**Comment by lionel-** [comment]
@yutannihilation On second thought let's keep this closed as we don't plan to make `where()` more complicated for now. You can use predicate combinators (it'll have to be your own implementations in helper functions though) to reduce the verbosity somewhat.

**Comment by yutannihilation** [comment]
Fair enough. After two years since I fined this issue, honestly I don't feel the need of this much. I was asking on https://github.com/r-lib/tidyselect/issues/248#issuecomment-1210933130 just because I was curious. Thanks for clarifying!
