### ISSUE TITLE
Technical description should have more clear example about the difference between ! and -

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/tidyselect#203]
As [the doc](https://tidyselect.r-lib.org/articles/syntax.html#dots-c-and-unary-) describes

> In this case, unary `-` is syntax for set complement. Unary `-` and `!` are equivalent:

we might think they are completely the same. But, they are NOT equivalent when there's some preceding selection. I think the section has some example to highlight the difference like this (we might want to replace the use of `iris` before doing this, though):

``` r
library(tidyselect)
library(magrittr)

select_loc <- function(data, ...) {
  eval_select(rlang::expr(c(...)), data)
}

iris %>% select_loc(c(starts_with("Sepal"), !Sepal.Length))
#> Sepal.Length  Sepal.Width Petal.Length  Petal.Width      Species 
#>            1            2            3            4            5

iris %>% select_loc(c(starts_with("Sepal"), -Sepal.Length))
#> Sepal.Width 
#>           2
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
This behaviour of unary `-` is an exception for dots documented in the next section https://tidyselect.r-lib.org/articles/syntax.html#dots-c-and-unary-

Maybe just needs a mention that there is a (big) exception to the general behaviour.

**Comment by yutannihilation** [comment]
Hmm, OK, just mentioning sounds enough to me.

One more question, is it that this is not a supposed usage of `!`

``` r
iris %>% select_loc(c(starts_with("Sepal"), !Sepal.Length))
```

and we should stick with boolean form if we use `!`?

``` r
iris %>% select_loc(starts_with("Sepal") & !Sepal.Length)
```

**Comment by lionel-** [comment]
I think I would favour the boolean form just because this way it's clearer what the operation is. With `c()`, it might not be obvious it's taking the union rather than the intersection.

**Comment by yutannihilation** [comment]
Thanks, I too feel the boolean form is better.
