### ISSUE TITLE
eval_resolve() for partial evaluation

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tidyselect#207]
@lionel- and I discussed a potential solution to the following issue:

```r
x <- c("x1", "x2")

wf <- workflow() %>%
  add_variables(y, c(all_of(x), x3)) %>% # <- quosure captured here
  add_model(linear_model)

fit(wf, data) # <- data is here
```

In the above example, `add_variables()` currently has to capture tidyselect expressions as quosures and delay evaluation until `fit()` is called with data. This can potentially result in capturing large environments. tidymodels users often serialize their workflows, which can result in abnormally large objects because of these quosures. recipes has a similar issue.

An alternative is to call a function like `eval_resolve()` from inside `add_variables()`. It would resolve the env-expressions that could be immediately evaluated, and would essentially inline them. It would return a pure expression, rather than a quosure, which workflows could cheaply hold onto until it needs to evaluate the data-expressions in the `fit()` call.

Special env-expressions like `starts_with(foo)` that require some amount of laziness would be handled so that `foo` gets evaluated and inlined, but `starts_with()` itself doesn't. The only env-expressions that require this laziness are native to tidyselect, so Lionel thinks they could all be handled without missing any edge cases.

**Comment by lionel-** [comment]
I think it would be a `crate()` function not an `eval()` function.

**Comment by lionel-** [comment]
> The only env-expressions that require this laziness are native to tidyselect, so Lionel thinks they could all be handled without missing any edge cases.

Any function that calls `peek_vars()` will need laziness, not just tidyselect ones. Also the tidyselect selectors may be wrapped in other functions. That's why I think we might need a protocol for returning a crate expression, and maybe conditions would be a good way.

Example case that needs to work:

```r
starts_with_s <- function() starts_with("s")
add_variables(starts_with_s())
```

The big downside is that this would require these lazy selectors to be trailing, including in wrappers, otherwise evaluation will be truncated. E.g. you can no longer do

```r
my_selector <- function() intersect(starts_with("s"), ends_with("s"))
```

This will require the selection helper to understand the crating protocol:

```r
my_selector <- function() {
  signal("", "tidyselect_crate", expr = quote(mypkg::my_selector())

  intersect(starts_with("s"), ends_with("s"))
}
```

**Comment by lionel-** [comment]
May be wrapped for convenience as one of these:

```r
signal_crate(mypkg::my_selector)
signal_crate("mypkg", "my_selector")
```

This helper takes a namespaced symbol of the function to call. It would then look at the relevant `sys.call()` to evaluate all supplied arguments to be inlined in the crated call.

**Comment by DavisVaughan** [comment]
I think we probably need to re-evaluate what we do in workflows / recipes to see if we still really need this or if there is anything we can do on our end to avoid getting into the situation where this is a problem.

So we can close now and re-open later if we think it is an issue still
