### ISSUE TITLE
Where did where() go?

### ISSUE THREAD

**Issue by IsadoraBM** [r-lib/tidyselect#210]
Unable to load where() from tidyselect, despite re-installing tidyselect, tidyr, and tidyverse.

**Comment by lionel-** [comment]
Please post a reprex.

**Comment by lionel-** [comment]
I'm assuming you're trying to do `tidyselect::where`? This function isn't currently exported but we plan to. You can still use it in tidyselect contexts. Let me know if there's another issue.

**Comment by IsadoraBM** [comment]
Yes, I mean tidyselect::where(). What do you mean "in tidyselect contexts"?
Can you explain how I can access its functionality in the meantime?

**Comment by IsadoraBM** [comment]
Ah ok! I was confused because typing tidyselect::wh wasn't autocompleting
to where() but it works. I've asked a question about negating or combining
where() with if_else on stackoverflow
<https://stackoverflow.com/questions/63696571/replacing-mean-from-psychdescribe-for-mode-in-dataframe>.
I'd be interested to know if this question prompts an additional
feature for where() down the road.
