### ISSUE TITLE
tidyselect does not export `where`

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/tidyselect#213]
I am writing an R package that imports various tidyselect functions. I noticed I can import almost all select helpers like `all_of`, but I cannot import `where` (it's not exported in namespace). My use case is to use it with `dplyr::mutate(where(...))`

**Comment by lionel-** [comment]
Duplicate of #209.

We'll export in the next release. You don't need to import it to use it though, just use `utils::globalVariables("where")` in the meantime.
