### ISSUE TITLE
eval_select(, <unnamed empty list>)

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/tidyselect#214]
This is related to https://github.com/tidyverse/dplyr/issues/5523, perhaps `eval_select()` can allow unnamed vectors when they are empty, and just pretend it's `character()` ?

``` r
tidyselect::eval_select(NULL, list())
#> Error: Can't select within an unnamed vector.
#> Backtrace:
#>     █
#>  1. └─tidyselect::eval_select(NULL, list())
#>  2.   └─tidyselect:::eval_select_impl(...)
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
The problem upstream problem appears to have been resolved:

``` r
library(dplyr, warn.conflicts = FALSE)
tibble(.rows = 5) %>% mutate(across(NULL, ~ .x + 1))
#> # A tibble: 5 × 0
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Probably because this now works:

``` r
tidyselect::eval_select(NULL, data.frame())
#> named integer(0)
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
