### ISSUE TITLE
Failed to install tidyselect from GitHub

### ISSUE THREAD

**Issue by muriloneo** [r-lib/tidyselect#222]
Hello,
I am trying to install this to a CentOS 7 server but I'm failing every try.

Can someone please help me?

`remotes::install_github("r-lib/tidyselect")
Downloading GitHub repo r-lib/tidyselect@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: magrittr (1.5 -> 2.0.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates:3
   During startup - Warning message:
   Setting LC_CTYPE failed, using "C" 
v  checking for file '/tmp/RtmpP09UTv/remotesd95bcaa318/r-lib-tidyselect-fe65d19/DESCRIPTION' ...
-  preparing 'tidyselect':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'tidyselect_1.1.0.9000.tar.gz'
   
Installing package into '/home/ec2-user/R/x86_64-pc-linux-gnu-library/3.6'
(as 'lib' is unspecified)
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'tidyselect' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpP09UTv/filed95799204e5/tidyselect_1.1.0.9000.tar.gz' had non-zero exit status
`

`R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.
`

**Comment by lionel-** [comment]
Sorry for not getting back, I hope you found a solution.
