### ISSUE TITLE
Optionally suppress use of predicates

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#226]
e.g. `eval_select(..., allow_predicates = FALSE)`. This would be useful for dbplyr, where we can't easily compute predicates.

**Comment by roni-fultheim** [comment]
@hadley 
Has this been fixed?
I have been trying to summarize across numeric columns using `summarise(across(where(is.numeric)))` and it took me quite a while to figure out the reason for the error.
Is there any substitute for using `is.numeric` besides for naming all columns?
Thank you

**Comment by roni-fultheim** [comment]
@hadley 
For some unclear reason this code 1) does not fail as the non-negation does, 2) applies given function to all variables (numeric and non-numeric)

`library(ggplot2)
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
diamonds %>% lazy_dt() %>% 
    group_by(color) %>%
    summarise(across(!where(is.numeric), first))`

unlike the equivalent statement using a data frame which only returns the relevant variables
`diamonds %>% 
    group_by(color) %>%
    summarise(across(!where(is.numeric), first))`

**Comment by lionel-** [comment]
@roni-fultheim Can you open dbplyr / dtplyr issues?

**Comment by roni-fultheim** [comment]
Yes, sorry

**Comment by hadley** [comment]
Closing in favour of more holistic solution in #242
