### ISSUE TITLE
str_detect() inside where()

### ISSUE THREAD

**Issue by michalovadek** [r-lib/tidyselect#228]
Based on the description of where(), ("This selection helper selects the variables for which a function returns TRUE."), I would expect the following to work:

```{r}
tibble(asd = c(1,2,3),
       Asd = c(1,2,3)) %>%
   select(where(~str_detect(.,"^[:lower:].*")))
```

given that

```{r}
stringr::str_detect(c("asd","Asd"), "^[:lower:].*")
```

works as per usual. Instead the first call returns

```{r}
Error: `where()` must be used with functions that return `TRUE` or `FALSE`.
```

Should I not be expecting where() + str_detect() to work? contains() does not work here either.

**Comment by lionel-** [comment]
The function inside `where()` is being passed the column vectors, not the column names. So `str_detect()` is getting `c(1, 2, 3)` as input (I'm surprised it doesn't throw an error).

You're looking for `matches()`:

```r
df %>% select(matches("^[a-z].*"))
```

**Comment by michalovadek** [comment]
I see. `select(matches("^[a-z].*"))` does not work for me though either on the example above. It selects both "Asd" and "asd" which is not the desired behaviour.

**Comment by yutannihilation** [comment]
It needs `ignore.case = FALSE`.
