### ISSUE TITLE
Instrument predicate errors?

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#233]
For tidyverse/dplyr#5847.

- Missing `where()` errors
- Vectorised predicate errors

**Comment by hadley** [comment]
Do you remember what you were thinking here? I skimmed the linked issue and it's not obvious to me what `where()` needs.

**Comment by lionel-** [comment]
I think it had something to do with adding classes to predicate errors so that dplyr could catch them, but I'm not sure. I don't understand my own notes 😬.

**Comment by lionel-** [comment]
Let's just close this until the next time we need something for `if_any()` or `if_all()`.
