### ISSUE TITLE
Predicate to determine whether input is a pure data-expression

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#235]
Or if it includes env-expressions.

Pure data-expressions might be optimised away but not env-expressions.

**Comment by DavisVaughan** [comment]
This somehow feels related to https://github.com/r-lib/tidyselect/issues/207, which would need some way to determine this?

**Comment by hadley** [comment]
Closing, since it's mostly useful for teaching, and probably not worth the implementation cost.
