### ISSUE TITLE
where() with NA values

### ISSUE THREAD

**Issue by MyKo101** [r-lib/tidyselect#236]
The `where()` function produces relatively uninformative errors when functions output `NA` values. It would be useful for the user if this was checked.

In this example, the function, `~any(str_detect(.x,","))` returns `TRUE` and `FALSE` values, but also returns `NA` values, and so the below throws an uninformative error:
```
gss_cat %>%
  select(where(~any(str_detect(.x,","))))
Error: `where()` must be used with functions that return `TRUE` or `FALSE`.
```

This can be rectified using `na.rm=T` in the `any()` function, as below:
```
gss_cat %>%
  select(where(~any(str_detect(.x,","),na.rm=T)))
```

I believe that having this throw an error is important, as it draw attention to the `NA` values, but since all the values are `logical`, the error should be more informative.

This is also in contrast to the `select_if()` version of this call:
```
gss_cat %>%
  select_if(~any(str_detect(.,",")))
```

which treats `NA` values the same as `FALSE`

**Comment by NeuronalMike** [comment]
I believe this is a limitation with the anonymous function you have used rather than an issue with the where() function .

`
fruit <- c("apple", "banana", "pear", "pinapple", NA)
stringr::str_detect(fruit, "a")
# TRUE TRUE TRUE TRUE   NA
`
Open to being wrong, though I do believe its a limit of the stringr::str_detect function. Maybe stringr or string has a better alternative?

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(
  a = c("x", NA), 
  b = c(NA, NA), 
  c = c("y", "y")
)

df |> select(where(~ any(stringr::str_detect(.x, "x"))))
#> Error in `FUN()`:
#> ! `where()` must be used with functions that return `TRUE` or `FALSE`.
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Interestingly the problem doesn't occur with `grepl()` because it appears to never match missing strings.
