### ISSUE TITLE
`c()` vs. `...` in tidy selection

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/tidyselect#239]
I use tidyselect in a package of mine. Currently I have defined internal helpers to differentiate between selection using `c()` and `...`. However it seems to work if only relying on the `...` version.

In this example below it seems like using `tidyselect_dots()` works even when taking an input that I would normally use `tidyselect_vec()` for.
``` r
library(tidyselect)
library(rlang)
library(magrittr)

tidyselect_vec <- function(data, expr) {
  eval_select(enquo(expr), data)
}

tidyselect_dots <- function(data, ...) {
  eval_select(expr(c(...)), data)
}

# Uses tidyselect_dots in a place that tidyselect_vec is recommended
select_cols <- function(data, cols = everything()) {
  tidyselect_dots(data, {{ cols }})
}

df <- data.frame(x = 1:3, y = 1:3, z = 1:3)

df %>%
  select_cols(cols = c(x:z, -y))
#> x z 
#> 1 3
```

Is there any reason why I shouldn't always use `tidyselect_dots()`? None of my unit tests fail when making this change, but I wasn't sure if there was some underlying reason that my tests just didn't happen to catch.

**Comment by lionel-** [comment]
The two approaches should be completely equivalent and you can use the one that makes the most sense in the context of your package. We have chosen the single expression interface to align with `eval()`, and also to make it clear that `...` handling is powered by `quote(c(...))`. This wasn't always the case, in earlier versions of tidyselect the dev-facing entry-point took `...` as input, and these dots were behaving slightly differently to inputs passed inside `c()`.

The more important choice is whether your functions take `...` like `dplyr::select()` or a single tidyselect argument like `tidyr::pivot_longer()`. This depends on what your functions are doing. If they operate on a selection with multiple parameters, a named argument is likely better. If they collect a set of columns, dots are more appropriate.

**Comment by markfairbanks** [comment]
Gotcha - makes sense. Thanks for the clarification!
