### ISSUE TITLE
Please consider exporting `where()`

### ISSUE THREAD

**Issue by MattCowgill** [r-lib/tidyselect#240]
It would be nice to be able to use `tidyselect::where()` in functions in other packages. It does not currently appear to be exported.

**Comment by lionel-** [comment]
Duplicate of #201.

tidyselect is a domain-specific language that is specially interpreted. This means `where()` is not a real function and you can use it in your package without a namespace qualifier. Just use `utils::globalVariables("where")` to avoid a note. We'll export it in the next version to make this more intuitive.

**Comment by MattCowgill** [comment]
OK, thank you for clarifying.
