### ISSUE TITLE
Support for lazy tibbles

### ISSUE THREAD

**Issue by mgirlich** [r-lib/tidyselect#242]
Lazy tibbles currently have two issues with `eval_select()`:

1. They are not a vector so one has to simulate a "dummy" tibble with the appropriate column names, e.g with `dtplyr:::simulate_vars()`.
2. The column types are not generally known which is why `allow_predicates` would make sense: #226

The second point is still a bit annoying when trying to do some general work in a generic, e.g. in `tidyr::nest()` unnamed dots are tried to be named

```r
tidyr::nest <- function (.data, ..., .names_sep = NULL, .key = deprecated()) {
  cols <- enquos(...)
  if (any(names2(cols) == "")) {
    col_names <- names(tidyselect::eval_select(expr(c(...)), .data))
    ...
  }
  UseMethod("nest")
}
```

So, it would be necessary to check the type to figure out whether `allow_predicate` should be `TRUE` or `FALSE`. It might make sense if `tidyselect()` could handle this.

Also see https://github.com/tidyverse/tidyr/issues/1134

**Comment by hadley** [comment]
Note that there are at least two lazy tibble variants, one in dbplyr and the other in dtplyr.

**Comment by hadley** [comment]
One possibility would be to provide a `tidyselect_proxy` generic. It could return `list(data, supports_predicates).

**Comment by hadley** [comment]
Better to do `tidyselect_proxy()` + `tidyselect_supports_predicates()`.
