### ISSUE TITLE
tidyselect::where() not an exported object from 'namespace:tidyselect'

### ISSUE THREAD

**Issue by NeuronalMike** [r-lib/tidyselect#244]
Hi there Authors, 

When trying to prefix where() from the tidyselect package, I keep getting the following error. It it doesn't appear when I prefix other Tidyselect functions such as tidyselect::starts_with() or tidyselect::contains() so its likely a simple fix of exporting the function.

Tibble_Table_Of_Data %>% 
	dplyr::select(tidyselect::where(is.character))

![2021-08-20 13-20-24](https://user-images.githubusercontent.com/25239347/130174019-077d4959-0768-4b27-a674-d14ac41d7a17.png)

Error: 'where' is not an exported object from 'namespace:tidyselect' Run `rlang::last_error()` to see where the error occurred.
24.stop(fallback)
23.signal_abort(cnd)
22.abort(conditionMessage(cnd), parent = cnd)
21.h(simpleError(msg, call))
20..handleSimpleError(function (cnd) { abort(conditionMessage(cnd), parent = cnd) }, "'where' is not an exported object from 'namespace:tidyselect'", ...
19.eval_tidy(expr, context_mask)
18.eval_context(expr, context_mask)
17.walk_data_tree(new, data_mask, context_mask)
16.reduce_sels(node, data_mask, context_mask, init = init)
15.eval_c(expr, data_mask, context_mask)
14.walk_data_tree(expr, data_mask, context_mask)
13.vars_select_eval(vars, expr, strict, data = x, name_spec = name_spec, uniquely_named = uniquely_named, allow_rename = allow_rename, type = type)
12.withCallingHandlers(expr, simpleError = function(cnd) { abort(conditionMessage(cnd), parent = cnd) })
11.instrument_base_errors(expr)
10.doTryCatch(return(expr), name, parentenv, handler)
9.tryCatchOne(expr, names, parentenv, handlers[[1L]])
8.tryCatchList(expr, classes, parentenv, handlers)
7.tryCatch(instrument_base_errors(expr), vctrs_error_subscript = function(cnd) { cnd$subscript_action <- subscript_action(type) cnd$subscript_elt <- "column" cnd_signal(cnd) ...
6.with_subscript_errors(vars_select_eval(vars, expr, strict, data = x, name_spec = name_spec, uniquely_named = uniquely_named, allow_rename = allow_rename, type = type), type = type)
5.eval_select_impl(data, names(data), as_quosure(expr, env), include = include, exclude = exclude, strict = strict, name_spec = name_spec, allow_rename = allow_rename)
4.tidyselect::eval_select(expr(c(...)), .data)
3.select.data.frame(., tidyselect::where(is.character))
2.dplyr::select(., tidyselect::where(is.character))
1.StoreConsent %>% dplyr::select(tidyselect::where(is.character))

Many thanks :)

**Comment by lionel-** [comment]
Hello, see stickied issue #201.

**Comment by Rey-ND** [comment]
Thanks Lionel :)
