### ISSUE TITLE
A more efficient `&` and `|` ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/tidyselect#260]
See the following example : 

``` r
library(dplyr, w = F)
system.time(
  select(band_members, name & where(~ {Sys.sleep(1); is.character(.)}))
)
#>    user  system elapsed 
#>   0.004   0.001   2.011
```

It takes 2 seconds but we know from the `lhs` of `&` that we had a single candidate so it might have taken only 1 second.

I understand that : 
* (1) Tidy selection is usually fast anyway
* (2) `&` is traditionally commutative 

But : 

* (1) tidy selection can be applied on more than data frames and in some cases the conditions that are applied to the data (through where() or custom helpers)  might take time
* (2) we're already redefining `&` to work on numeric values anyway and it would stay functionally commutative (unless we really care about the rhs potentially failing on items dismissed by lhs), users worried about efficiency might just put the expensive condition last.

I don't believe there is an easy way at the moment to compute efficiently `select(data, cheap_selection_1(), cheap_selection_2() & expensive_selection())`

An alternative would be to have `&&` as well, but I think I'd be personally happier with an enhanced `&`.

The same principle apply to `|` and comma separated selections, if a selection is already validated there's no need to go through it again unless it's negative (and then the negated selection should only consider previously selected items).

```
library(dplyr, w = F )
system.time(
  select(band_members, name | where(~ {Sys.sleep(1); is.character(.)}))
)
#>    user  system elapsed 
#>   0.009   0.001   2.021

system.time(
  select(iris, Species, Sepal.Length, -where(~ {Sys.sleep(1); is.numeric(.)}))
)
#>    user  system elapsed 
#>   0.005   0.000   5.027
```

**Comment by lionel-** [comment]
Performance is currently not a priority for tidyselect. I think this suggested enhancement is out of scope.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
