### ISSUE TITLE
More flexible errors for `eval_select()` ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/tidyselect#264]
`eval_select()` assumes that we are using tidy selection in a table, 

```
iris_list <- as.list(iris)
tidyselect::eval_select(quote(Specie), iris_list)
#> Error in `chr_as_locations()`:
#> ! Can't subset columns that don't exist.
#> x Column `Specie` doesn't exist.
```

With a bit of digging in the code, I found this pattern :

```
tryCatch(
  tidyselect::eval_select(quote(Specie), iris_list) , 
  vctrs_error_subscript = function(cnd) {
    cdn$subscript_elt <- "element"
    rlang::cnd_signal(cnd)
  }
)
#> Error in `chr_as_locations()`:
#> ! Can't subset elements that don't exist.
#> x Element `Specie` doesn't exist.
```

It's limited to some keywords though. "element" is quite general but it would be nice to be able to provide a custom name there. Moreover I believe the `vctrs_error_subscript` name is an implementation detail so I think I can't assume it to work in future versions.

Is there a way that I miss to customise these errors ? And if not could we provide a custom term to `tidyselect::eval_select()` to do so ?

**Comment by lionel-** [comment]
We restricted this set on purpose to allow consistent translations to other languages.

**Comment by moodymudskipper** [comment]
It makes sense, but then is my `tryCatch()` call the appropriate way to change `column` to `element` ?

**Comment by lionel-** [comment]
yup except you should never use `tryCatch()` to rethrow an error because it prevents `recover()` and `traceback()` from reaching into the inner context. See https://rlang.r-lib.org/reference/topic-error-chaining.html
