### ISSUE TITLE
Out of context `all_of()` should error

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#269]
```r
tidyselect::all_of("x")
#> [1] "x"

tidyselect::any_of("x")
#> Error:
#> ! `any_of()` must be used within a *selecting* function.
#> ℹ See <https://tidyselect.r-lib.org/reference/faq-selection-context.html>.
```

**Comment by hadley** [comment]
I think it's worth looking into this, but I suspect there's some reason (i.e. a revdep failure?) that this doesn't already error.

**Comment by johnaponte** [comment]
How to proceed with selecting columns with an external vector in summarize_at?:

I got this warning if using vars() with summarize_at:

## Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
## ℹ Please use `all_of()` or `any_of()` instead.
##   # Was:
##   data %>% select(anavars)
## 
##   # Now:
##   data %>% select(all_of(anavars))
## 
## See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.

And got this warning if using all_of()

## Warning: Using `all_of()` outside of a selecting function was deprecated in tidyselect
## 1.2.0.
## ℹ See details at
##   <https://tidyselect.r-lib.org/reference/faq-selection-context.html>

**Comment by lionel-** [comment]
@johnaponte Can you please show your code, ideally with a reprex?
