### ISSUE TITLE
Should `matches` use `perl = TRUE`?

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#330]
I doubt this will affect any existing code, but does make the pattern syntax a bit closer to stringr.

**Comment by ant-durrant** [comment]
I just came here to check whether `\p{}` not being supported was possibly a bug and saw that `perl = FALSE` is the culprit.

Put that as at least one vote for yes!

From the docs:

> For matches() this is a regular expression, and can be a stringr pattern.

I am aware that using `grep()` `sub()` I have to think about a `perl` flag, but I am not aware of ever thinking about it when using tidyverse stuff.

Just checked, and yep - at least `stringr::str_detect()` does not have `perl` as an argument, so if it is to be included, having the default as `TRUE` makes sense for me.
