### ISSUE TITLE
Allow regex operators in starts_with and ends_with

### ISSUE THREAD

**Issue by carlganz** [r-lib/tidyselect#332]
Based on the docs maybe you want to keep this an exact match but with `stringr` regex operators work in the starts and ends helpers

```{r}
library(tidyverse)

# For better printing
iris <- as_tibble(iris)

iris %>% select(starts_with("Sepal|Petal"))

str_starts(colnames(iris), "Sepal|Petal")
```

I can make a pretty quick PR if anyone wants this

**Comment by lionel-** [comment]
yes it's supposed to be an exact match. You can use `matches()` if you need regexes.
