### ISSUE TITLE
stacks does not recognize the control statement in fit_resamples or tune_grid

### ISSUE THREAD

**Issue by amin0511ss** [r-lib/tidyselect#342]
I am trying to stack two models: ranger (randomeforest) and lighgbm from bonsai. I fit resamples via respective workflows and include the control_stack_resamples argument. Both workflows use the same recipe as follows.
receipe_mixed_undersample <- 
    recipe(Disposition ~ ., data = Data202101_train) %>%
    step_lencode_mixed(RuleCombination, outcome = vars(Disposition)) %>% 
    step_nzv( all_predictors(), options = list(freq_cut = 95/5, unique_cut = 10 )) %>%
    step_corr( all_numeric(), - all_outcomes(), threshold = 0.9 ) %>%
    step_downsample (Disposition, under_ratio = 1) %>%
    step_cut(BankCustomer, breaks = 1) 

cv folds:
resample_folds <- vfold_cv(Data202101_train, v=5,repeats = 3, strata = Disposition)

workflows and fit:
stacks_lgbm_mixed_undersample_workflow <- 
     workflow() %>%  add_recipe(receipe_mixed_undersample) %>% add_model(last_lgbm_mixed_undersample_model)
   
  lgbm_res <- 
    stacks_lgbm_mixed_undersample_workflow %>% 
    fit_resamples(resamples = resample_folds,metrics = metric_set(mn_log_loss,mcc,bal_accuracy,roc_auc), 
                  control_stack_resamples(save_pred = TRUE, save_workflow = TRUE))
  

  stacks_rf_mixed_undersample_workflow <-
    workflow() %>%  add_recipe(receipe_mixed_undersample) %>% add_model(last_rf_mixed_undersample_model) 
  
  rf_res <- 
    stacks_rf_mixed_undersample_workflow %>% 
    fit_resamples(resamples = resample_folds,metrics = metric_set(mn_log_loss,mcc,bal_accuracy,roc_auc),
                  control_stack_resamples(save_pred = TRUE, save_workflow = TRUE))

The models run fine and produce result but when i try to add candidate, i get the error message below:

 My_data_st <- 
    stacks() %>%
    add_candidates(lgbm_res) %>%
    add_candidates(rf_res) 

Error in `add_candidates()`:
! The inputted `candidates` argument was not generated with the appropriate control settings. Please
  see [`control_stack()`](stacks::control_stack).
Run `rlang::last_error()` to see where the error occurred.

Could someone please advise as to what i need to do.
thank you

**Comment by amin0511ss** [comment]
I also tried with xgboost and ranger because i thought it might have to do with including bonsai model. I still get the same error message.

**Comment by lionel-** [comment]
Thanks!
