### ISSUE TITLE
Don't error when dropping nonexistent columns

### ISSUE THREAD

**Issue by chrsigg** [r-lib/tidyselect#345]
Dropping a named column that does not exist in the table results in an error:

``` r
library(tidyverse)
my <- tibble(a = 1, b = 2)
my %>% select(-c)
#> Error in `select()`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `c` doesn't exist.
#> Backtrace:
#>      ▆
#>   1. ├─my %>% select(-c)
#>   2. ├─dplyr::select(., -c)
#>   3. ├─dplyr:::select.data.frame(., -c)
#>   4. │ └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
#>   5. │   └─tidyselect:::eval_select_impl(...)
...
```

<sup>Created on 2023-06-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

But arguably, there is no need for this error, returning the unmodified table instead would have given the correct result.

With a more tolerant behavior, code that wants to ensure that certain columns are not present in a table would no longer have to check first which column names are currently present.

**Comment by lionel-** [comment]
We're unlikely to make this less strict but you can use `select(-any_of("c"))` to explicitly get the tolerant behaviour.
