### ISSUE TITLE
Should vars_pull() have action semantics?

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#42]
It seems reasonable for it to accept variable name as symbol, string, or integerish. In what circumstance would you want to use a tidyselect helper?

I'm mostly interested in this in the context of https://github.com/tidyverse/tidyr/issues/372 - it seems like we could have a new semantics here where a symbol or constant means select from the existing data frame, and an expression means to compute values in the overscope. 

That seems more useful than allowing people to use tidyselect helpers when selecting a single variable, but it does introduce yet another new variable selection context that's part way between the existing select and mutate semantics.

**Comment by lionel-** [comment]
I think that would be useful. But this kind of complex evaluation semantics would probably require the IDE to somehow clearly convey how the expression is interpreted as the user is typing.

Would need a (likely long) deprecation process.

**Comment by hadley** [comment]
I no longer think this is worth the cost of implementing it.
