### ISSUE TITLE
Implement a slice() helper?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/tidyselect#47]
Useful for backends that implement `slice()`. The helper would convert arguments to `slice()` into two vectors: a sorted list of rows to fetch, and a map into that sorted list of rows.

Reference: https://github.com/krlmlr/fstplyr/issues/4#issuecomment-356963298.

**Comment by lionel-** [comment]
Probably belongs in vctrs now. Perhaps `vec_as_index()` would be helpful?
