### ISSUE TITLE
select_helpers accept character vector?

### ISSUE THREAD

**Issue by ruaridhw** [r-lib/tidyselect#50]
Possible feature request though this may contradict #49 

Allow for natively passing a vector of strings to `starts_with`, `ends_with`, `contains` ... in order to avoid having to redefine the regex

Currently:
(1) Unwieldy manual list of single columns
```r
select(df,
       starts_with("a"),
       starts_with("b"),
       ends_with("c"),
       ends_with("d"),
       ...)
```

or

(2) Redefine matching regex for each `select_helper`
```r
long_list_of_select_vars <- c("a", "b", ...)
another_long_vector <- c("c", "d", ...)
select(df,
       matches(paste0("^(", paste(long_list_of_select_vars, collapse="|"), ")")),
       matches(paste0("(", paste(another_long_vector, collapse="|"), ")$")))
```

Request:
```r
select(df,
       starts_with(c("a", "b")),
       ends_with(c("c", "d")),
       ...)
```
which would have the same behaviour as (1)

[For context](https://stackoverflow.com/questions/42125049/using-starts-with-in-dplyr-with-a-vector-of-partial-column-names)

**Comment by huftis** [comment]
The PR at https://github.com/tidyverse/dplyr/pull/2958 (never commited) changed the semantics so that:

    Selecting verbs (e.g. `select()` or verbs supporting `vars()`
    selections) now treat symbols a bit differently. Symbols are only
    evaluated in the data context, never in the calling context (#2904).
    This means that you can no longer refer to local variables unless
    you are explicitly unquoting these variables with `!!`.
    
    Note that since last version, helper calls (like `starts_with()`)
    obey the opposite behaviour and are evaluated in the calling
    context, not the data context. To sum up, symbols can only refer to
    data frame objects, while helpers can only refer to contextual
    objects.

(Source: https://github.com/tidyverse/dplyr/pull/2958/commits/331ed4ea4f0fbf703121e7e8258af8baf2023ba7)

As long as it’s documented, that sounds like a reasonable behaviour, IMHO.
