### ISSUE TITLE
Warning if names of duplicated selected variables do not agree

### ISSUE THREAD

**Issue by thackl** [r-lib/tidyselect#52]
I get the idea of having select deduplicate column names/indices, but wouldn't some form of warning make sense? Here one particularly quirky example: the position of the column seems to be determined by the first appearance of the duplicated index, but the name by the last appearance.

(First mentioned in https://github.com/tidyverse/dplyr/issues/2354)

```R
tibble(x="A",y="B") %>%
  select(y=2, x=1, z=2)
# A tibble: 1 x 2
  z     x    
  <chr> <chr>
1 B     A 
```

**Comment by krlmlr** [comment]
The returned tibble should have columns (y, x) instead of (z, x). I don't think the names and positions should agree, but a warning (error?) for duplicate indexes seems helpful.

**Comment by lionel-** [comment]
We need to allow duplicate indexes because helpers' selections might overlap, the warning should only arise when duplicates are assigned different names. WDYT @hadley?

**Comment by hadley** [comment]
Good idea, but low priority. We can talk about when we next work on tidyselect
