### ISSUE TITLE
Selecting the same variable twice with different names

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/tidyselect#59]
``` r
tidyselect::vars_select( names(iris), a = Species, b = Species)
#>         b 
#> "Species"
```

originally in https://github.com/tidyverse/dplyr/issues/3499

**Comment by krlmlr** [comment]
I'm not sure `select()` should duplicate columns.

**Comment by VincentGuyader** [comment]
@krlmlr dont remember the use case :)
In my view select should duplicate the columns. Or at least return a warning in this case.

Regards

**Comment by lionel-** [comment]
Duplicate of #52.
