### ISSUE TITLE
Support functions in selections

### ISSUE THREAD

**Issue by lionel-** [r-lib/tidyselect#86]
Once we have https://github.com/r-lib/rlang/issues/726, we can extend the selection DSL with predicate functions. Those would expand to a vector of column positions.

```r
data %>% select(is.numeric)

data %>% select(-c(is.numeric, one_of(nms)))
```

This would make the `_if` scoped variants in dplyr largely irrelevant. Also the `_all` variants are just `_at(vars(everything())`, so if we came up with a more concise syntax we wouldn't need those either. The successors of scoped variants could be just one function.

cc @romainfrancois @hadley

**Comment by romainfrancois** [comment]
🤔 I guess `each()` would be confusing because of history, but something like this would be nice: 

```r
iris %>% 
  mutate(each(vars(-is.factor), ~mean(.))
```

i.e. having it inside the `mutate()` rather than as a suffix

**Comment by lionel-** [comment]
Yes though still not clear what's the best name. Called without arguments, it just materialises the current tibble, so `each()` might not be right. Maybe `sels()` is still right. Unfortunately `cols()` is already taken in readr. Maybe `tib()`?

By the way, @hadley has suggested making it a quoting function so you'd use it like this:

```r
data %>% mutate(tib(-is.factor, mean, na.rm = TRUE)
data %>% mutate(tib(starts_with("d"), ~ mean(., na.rm = TRUE))
```

When you give a name to the tibble, it becomes a df-col instead of being auto-spliced. This would create a df-col without transforming the columns:

```r
data %>% mutate(df = tib())
data %>% mutate(df = tib(-is.factor)
```

Which will be especially nice with `morph()` proposed in https://github.com/tidyverse/dplyr/issues/3721.

**Comment by romainfrancois** [comment]
You mean we would not need `vars()` ? 

How would you e.g. `mean()` all the non factors that start with `S` ? 

```r
data %>% mutate(tib(-is.factor, starts_with("S"), mean, na.rm = TRUE)
```

I guess not because `...` are for additional arguments to the function ?

**Comment by lionel-** [comment]
Oh you just use `c()`:

```r
data %>% mutate(tib(c(-is.factor, starts_with("S")), mean, na.rm = TRUE)
```

**Comment by romainfrancois** [comment]
`pick()` ?

**Comment by lionel-** [comment]
Would it be crazy to interpret `*` not as a predicate function but as a shortcut for `everything()`?

```r
data %>% mutate(pick(`*`, mean, na.rm = TRUE))
```

**Comment by romainfrancois** [comment]
The backticks make it less compelling than if you could just use *

**Comment by lionel-** [comment]
Right I guess `pick("*")` is more user-friendly. You could still select a `"*"` column with `one_of("*")`.

**Comment by hadley** [comment]
I wondered if it should default to selecting all columns

**Comment by lionel-** [comment]
I think it should, but the `"*"` shortcut would be useful for mapping over all columns because `everything()` is a long word to type.

```r
# Without the shortcut
data %>% mutate(pick( , mean, na.rm = TRUE))
data %>% mutate(pick(everything() , mean, na.rm = TRUE))

# With the shortcut
data %>% mutate(pick("*", mean, na.rm = TRUE))
```

**Comment by romainfrancois** [comment]
Feels type weird to special case a string, even if you can work around it with `one_of()`

**Comment by lionel-** [comment]
This is a DSL, `c(is.character, starts_with("foo"))` is type weird as well ;)

**Comment by lionel-** [comment]
Anyway, we can worry about a `all` shortcut later since we already have `everything()`.

**Comment by hadley** [comment]
Another approach is a function operator, which would take a vectorised function and return a colwise vectorised function (where the first argument is the column selection):

```R
data %>% mutate(col_(mean)(na.rm = TRUE))
data %>% mutate(col_(mean)(is.numeric, na.rm = TRUE))
data %>% mutate(col_(mean)(c(x, y), na.rm = TRUE))
data %>% mutate(col_(mean)(starts_with("x"), na.rm = TRUE))
```

Of course we'd provide common wrappers, yielding something more like:

```R
data %>% mutate(col_mean(na.rm = TRUE))
data %>% mutate(col_mean(is.numeric, na.rm = TRUE))
data %>% mutate(col_mean(c(x, y), na.rm = TRUE))
data %>% mutate(col_mean(starts_with("x"), na.rm = TRUE))
```

**Comment by lionel-** [comment]
Interesting. I think the advantage of `pick()` over a function operator is that it seems easier to teach and learn as a bridge between dplyr and purrr, i.e. selection + mapping.

**Comment by hadley** [comment]
The thing that's  to me is that `mean` becomes an argument to `pick()`, instead of an argument to `mutate()`. That seems inside out.

We wouldn't have to teach `col_` very early because we'd teach `col_mean()` as an alternative to `mean()` when you wanted to compute multiple means instead of one. And then once you're used to that, I think `col_(otherfun)` will seem fairly natural. Most people won't actually understand how it works, but that'll be ok.

**Comment by romainfrancois** [comment]
in `col_(mean)(starts_with("x"), na.rm = TRUE)` we'd have the function `mean` potentially apart from its arguments `na.rm = TRUE`. 

If the selection is optional perhaps it should be at the end, something like: 

```
data %>% mutate(scoped(~mean(., na.rm = TRUE)))
data %>% mutate(scoped(~mean(., na.rm = TRUE), everything()))
data %>% mutate(scoped(~mean(., na.rm = TRUE), starts_with("S")))
```

**Comment by lionel-** [comment]
I suspect `pick()` might be the option that requires the fewest concepts to understand. In this version of dplyr, we'll support named and unnamed tibbles in action verbs and it will be important for users to learn about these semantics. Having a single verb that always returns a data frame, and that combines the familiar concept of selection with the (perhaps less familiar) concept of mapping seems to reduce the cognitive cost overall.

**Comment by lionel-** [comment]
One downside of bolting map with `pick()`: how do we map over tibbles created with action semantics?

With selections, we'd have:

```r
# no map
data %>% morph(new = pick(starts_with("d")))

# map
data %>% morph(new = pick(starts_with("d"), rescale))
```

With actions:

```r

# no map
data %>% morph(new = tibble(foo = foo * 3))

# map
?
```

Perhaps we are so focused on mapping because of the scoped variants, but with tibble support in dplyr we could use existing mapping tools like `modify()`.

```r
data %>% morph(new = modify(pick(starts_with("d")), rescale))
data %>% morph(new = tibble(foo = foo * 3) %>% modify(rescale))
```

This looks a bit more verbose though.

**Comment by lionel-** [comment]
`modify()` wouldn't work in summarising context because as a `[[<-` wrapper it always recycles results to the tibble size. It'd have to be `map_df()`. Similarly, a replacement for scoped variants would have to first create results and then entibble.

**Comment by moodymudskipper** [comment]
We could use formulas. The syntax would be light and unambiguous.

    data %>% select( ~is.numeric(.), one_of(nms)) 
    data %>% mutate( ~is.numeric(.) := ~mean(., na.rm = TRUE))
    # OR two sided formulas
    data %>% mutate(is.numeric(.) ~mean(., na.rm = TRUE))

    # could be simplifed when the terms are functions, though it might be weird
    data %>% select( ~is.numeric, one_of(nms))
    data %>% mutate(is.numeric ~ sqrt)

Maybe better, question mark operator would make it very intuitive (question => logical answer), would be parsed and no conflict risk with `?` 's standard use.

    data %>% select(? is.numeric, one_of(nms)) 
    # or even if it's not too weird, this would be easy to support
    data %>% mutate( ~is.numeric(.) := ~mean(., na.rm = TRUE))

Can be drafter quickly : 

``` r
library(tidyverse)
#> Registered S3 method overwritten by 'rvest':
#>   method            from
#>   read_xml.response xml2
#> Warning: package 'dplyr' was built under R version 3.6.1
`?` <- function(fun) {
  vars <- eval.parent(quote(tidyselect::peek_vars()))
  data <- eval.parent(quote(.))
  vars_lgl <- map_lgl(vars, ~fun(data[[.]]))
  which(vars_lgl)
}
starwars %>% select(?is.numeric, name)
#> # A tibble: 87 x 4
#>    height  mass birth_year name              
#>     <int> <dbl>      <dbl> <chr>             
#>  1    172    77       19   Luke Skywalker    
#>  2    167    75      112   C-3PO             
#>  3     96    32       33   R2-D2             
#>  4    202   136       41.9 Darth Vader       
#>  5    150    49       19   Leia Organa       
#>  6    178   120       52   Owen Lars         
#>  7    165    75       47   Beru Whitesun lars
#>  8     97    32       NA   R5-D4             
#>  9    183    84       24   Biggs Darklighter 
#> 10    182    77       57   Obi-Wan Kenobi    
#> # ... with 77 more rows
```

<sup>Created on 2019-08-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Formulas will be converted to functions.
