### ISSUE TITLE
Tidyselect functions should take a prototype as input

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#89]
Rather than a vector of variable names, as this would allow tidy select to also support type predicates.

(We'd need to transition to this gradually - probably first by adding a `ptypes` argument, then by deprecating vars, then removing vars)

**Comment by lionel-** [comment]
The problem with this approach is that tidyselect takes the base R vector view, not the vctrs vector view. If you want to select elements from a list, the prototype will contain no information about the names.

**Comment by hadley** [comment]
Where do we select elements from a list? That's definitely a rare case, so I don't think we should optimise for that (but maybe you're just arguing we shouldn't deprecate the old interface?)

**Comment by lionel-** [comment]
I think it's strange to take a prototype approach which is a vctrs concept and then use `names()` which is a base vector concept.

> but maybe you're just arguing we shouldn't deprecate the old interface

Yes I think so. Maybe adding `df_select()` and `df_select_vars()` makes sense? The former would return a data frame and the latter just names. If we ever want to allow actions within selections, the former could put the data mask in dynamic scope. Then we could have UIs like

```r
facet_grid(rows = starts_with("foo"), cols = acts(cut_number(foo, 3)))
```

**Comment by hadley** [comment]
We'd still returning a vector of names in either case. This is about the input interface.

**Comment by lionel-** [comment]
Yes as in `df_select_vars()`. But `df_select()` with input + output df might also make sense if we need to allow actions in selections.

**Comment by hadley** [comment]
When we make this new interface, I think we should also stop taking `...` and instead take a single `cols` argument.

**Comment by hadley** [comment]
This interface would have also prevented https://github.com/tidyverse/tidyr/pull/668

**Comment by lionel-** [comment]
Needs to return a named vector of variables instead of a prototype, as this is the only way to support on-the-fly renaming:

```r
mtcars %>% select(foo = cyl)
```

**Comment by lionel-** [comment]
Instead of supporting functions in selections (issue #86), it may be better to have a special kind of helper to inspect the prototypes? It might be clearer for users that the values cannot be inspected:

```r
data %>% select(types(is.character) | types(is.factor))

data %>% mutate(mapping(types(is.numeric)), standardise))
```

versus

```r
data %>% select(is.character | is.factor)

data %>% mutate(mapping(is.numeric, standardise))
```

**Comment by hadley** [comment]
I was thinking about this more — what's the downside of passing the entire data frame, not just the prototype? In cases where the data frame isn't available (like in dbplyr), we'd still use the prototype, but I think these cases will usually be obvious.

**Comment by lionel-** [comment]
I would favour this solution as it'd make it a simpler and more predictible API for users of the R backends.

**Comment by hadley** [comment]
And it should return numeric indicies, not a character vector.

**Comment by lionel-** [comment]
Numeric indices also make sense because they are very easy to use by client packages:

```r
# For selection:
set_names(x[inds], names(inds))

# For renaming:
names(x)[inds] <- names(inds)
```

Also with numeric indices we no longer need to return a vector as long as the input from `vars_rename()`.
