### ISSUE TITLE
rename_all fails on data.frame with dirty names

### ISSUE THREAD

**Issue by sfirke** [r-lib/tidyselect#93]
`rename_all` requires distinct, non-missing variable names in the input data.frame.  This is something of a circular problem for me: I want to use `rename_all` in `janitor::clean_names()` to address https://github.com/sfirke/janitor/issues/260 where grouping indices of a grouped_df are not updated along with the column names.

But the problematic variable names that often go into `clean_names()` are causing `rename_all` to fail.  For instance, with duplicated names, or missing names:

```r
# repeat names
test_df <- as.data.frame(matrix(ncol = 2))
names(test_df) <- c("repeat", "repeat")
test_df %>% rename_all(make.names)
#> `data` must be uniquely named but has duplicate columns

# missing names
test_df <- as.data.frame(matrix(ncol = 2))
names(test_df) <- c("hi", "")
test_df %>% rename_all(make.names)
#> Error in is_symbol(expr): argument "expr" is missing, with no default
```
(I'm using `make.names` to show it's not a `make_clean_names()` problem, but my actual use case would be calling `make_clean_names()`)
 
I welcome advice of all kinds - if there's a way I can get `clean_names()` to update the group names of a grouped_df without using `rename_all` that's great too 😃

**Comment by lionel-** [comment]
Related to #94.

**Comment by sfirke** [comment]
Thanks for working on this.  The two examples I have above still seem to be failing, though I'm using today's versions of dplyr, pillar, tibble, tidyselect, vctrs and the rlang from CRAN (2019-11-23).  Might you be able to include those cases as tests, that `rename_all` succeeds on data.frames with missing or duplicated column names?

Should I open a new issue?  Or actually, per the comment from Romain above, should it be two issues if these are caused by different underlying issues?

**Comment by lionel-** [comment]
Can you try with the unexported `tidyselect:::rename()` please?

dplyr still needs to be ported to use the new tidyselect API, but no need to open an issue there.

**Comment by sfirke** [comment]
I tried splicing `tidyselect:::rename()` into a new version of `dplyr::rename_all` - it still errored but maybe I'm doing that wrong.
```
library(dplyr)
rename_all_new <- function (.tbl, .funs = list(), ...) 
{
  funs <- dplyr:::as_fun_list(.funs, caller_env(), ...)
  vars <- tbl_vars(.tbl)
  syms <- dplyr:::vars_select_syms(vars, funs, .tbl, strict = TRUE)
  tidyselect:::rename(.tbl, !!!syms)
}

test_df <- as.data.frame(matrix(ncol = 2))
names(test_df) <- c("repeat", "repeat")
test_df %>% rename_all_new(toupper)

test_df_2 <- as.data.frame(matrix(ncol = 2))
names(test_df_2) <- c("hi", "")
test_df_2 %>% rename_all_new(toupper)
```

I tried calling it directly; I'm not sure how to pass it a renaming function, which is what would be needed with duplicated variable names (because they can't be distinguished by name).  But it seems to work in the case with the empty string variable name:
```
# works
test_df_2 %>%
  tidyselect:::rename("okay_name" = "")
```

**Comment by lionel-** [comment]
Thanks I'll look into it.

In the next version of dplyr the way to iterate colwise will be with `across()`. The current colwise verbs won't be deprecated to maintain backward compatibility, but they will stop being actively developed. `across()` will never work inside `rename()` or `select()` and it's unclear what is the way forward for this feature.

In the particular case of `rename_all()`, I would just use `set_names()` from purrr/rlang instead, you can pass a function instead of a vector of names.

```r

mtcars %>% set_names(toupper) %>% head()
#>                    MPG CYL DISP  HP DRAT    WT  QSEC VS AM GEAR CARB
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
```

Also note that while tidyselect now supports data frames containing duplicate names, you must repair them so they are unique. Calling `make.names()` without setting `unique = TRUE` would not work in any case.

```r
test_df %>% tidyselect:::rename()
#> Error: Names must be unique.

test_df %>% tidyselect:::rename(foo = 1)
#>   foo repeat
#> 1  NA     NA
```
